### ISSUE TITLE
Red Tutorial skin for SCP-035

### ISSUE THREAD

**Issue by xDanilor** [Exiled-Team/Scp035#22]
I'd like to ask if you could set the base skin of SCP-035 as a red version of the Tutorial role. That way using items wouldn't resort in bugs and the player would still look human, though a little "changed". Thanks ^^

**Comment by uncreativeCultist** [comment]
would be a nice option

**Comment by nomoemptypointer** [comment]
If you mean the PlayerInfo color, it can be changed, though model can't afaik

**Comment by FinnFurwolf** [comment]
You can change visible_role in the config to something else. I used Scientist, so you can actually see SCP-035 carrying a weapon.

**Comment by joker-119** [comment]
Model colors are not currently something thst can be changed.
