### ISSUE TITLE
Testing release issue

### ISSUE THREAD

**Issue by DinoNuggets2** [Exiled-Team/Scp035#5]
For some reason when I try to add the testing release of 035 to my server, it gives me this error and loads no configs:

[Exiled.Bootstrap] Exiled loading error: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'YamlDotNet, Version=11.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e' or one of its dependencies.

**Comment by joker-119** [comment]
Fixed in testing releases
