### ISSUE TITLE
Latest testing release errors

### ISSUE THREAD

**Issue by DinoNuggets2** [Exiled-Team/Scp035#6]
I get this error in console when the round is restarting:

[ERROR] [Exiled.Loader] Plugin "Scp035" threw an exception while enabling: HarmonyLib.HarmonyException: Patching exception in method System.Void Recontainer079::OnClassChanged(ReferenceHub hub, RoleType prevRole, RoleType newRole) ---> System.Exception: Wrong null argument: call NULL

and this just during normal gameplay:

[ERROR] [Exiled.Events] Method "OnEndingRound" of the class "Scp035.EventHandlers" caused an exception when handling the event "Exiled.Events.Events+CustomEventHandler`1[[Exiled.Events.EventArgs.EndingRoundEventArgs, Exiled.Events, Version=4.2.2.0, Culture=neutral, PublicKeyToken=null]]"
[2022-01-03 23:28:45.362Z] [ERROR] [Exiled.Events] System.NullReferenceException: Object reference not set to an instance of an object

**Comment by joker-119** [comment]
fuck

**Comment by joker-119** [comment]
Fixed in testing-releases

**Comment by MoHoseinHabibi** [comment]
When will the next release be published?
where can I get the testing-releases?
