### ISSUE TITLE
SCP-035 Badge dosent dissapear after death

### ISSUE THREAD

**Issue by DinoNuggets2** [Exiled-Team/Scp035#7]
Once SCP-035 dies and respawns, the red SCP-035 tag doesn't go away. They also still have the slow effect.
![SCPSL 1_3_2022 7_54_33 PM](https://user-images.githubusercontent.com/91291118/147995797-9009fa4b-98b6-414e-9e61-2842733d7c59.png)
.

**Comment by joker-119** [comment]
yikes

**Comment by joker-119** [comment]
How did they die?

**Comment by joker-119** [comment]
nvm, fixed
