### ISSUE TITLE
Testing-Release suggestion

### ISSUE THREAD

**Issue by DinoNuggets2** [Exiled-Team/Scp035#9]
-For the latest testing release version, possibly allow owners to configure the size of SCP-035. 
-Add a configuration for how much health 035 looses per configurable second(s)
-Make a configurable 035 spawn announcement(when someone becomes 035) and a configurable death announcement by CASSIE
-Make so SCP-035 cannot damage SCP's by shooting or any way of causing damage
-Add configurable hotkeys for 035 to use proximity chat and SCP chat. For example, Q for SCP chat and V for Proxy chat (proximity chat can be configurable)

**Comment by joker-119** [comment]
1. Already done in EXILED 5.0
2. Already done.
3. Already done.
4. Already done.
5. Impossible.
